export const mockCategories = {
  1: 'Science',
  2: 'Art',
  3: 'Geography',
  4: 'History',
  5: 'Entertainment',
  6: 'Sports',
};

export const mockQuestions = [
  {
    id: 1,
    question: 'What is the chemical symbol for water?',
    answer: 'H2O',
    category: 1,
    difficulty: 1,
    rating: 4,
  },
  {
    id: 2,
    question: 'What planet is known as the Red Planet?',
    answer: 'Mars',
    category: 1,
    difficulty: 2,
    rating: 3,
  },
  {
    id: 3,
    question: 'Who painted the Mona Lisa?',
    answer: 'Leonardo da Vinci',
    category: 2,
    difficulty: 2,
    rating: 5,
  },
  {
    id: 4,
    question: 'What is the largest ocean on Earth?',
    answer: 'Pacific Ocean',
    category: 3,
    difficulty: 2,
    rating: 3,
  },
  {
    id: 5,
    question: 'In which year did World War II end?',
    answer: '1945',
    category: 4,
    difficulty: 2,
    rating: 4,
  },
  {
    id: 6,
    question: 'Who directed the movie Schindler\'s List?',
    answer: 'Steven Spielberg',
    category: 5,
    difficulty: 3,
    rating: 5,
  },
  {
    id: 7,
    question: 'How many players are on a standard soccer team?',
    answer: '11',
    category: 6,
    difficulty: 1,
    rating: 3,
  },
  {
    id: 8,
    question: 'What is the speed of light in a vacuum (approximately)?',
    answer: '299,792,458 m/s',
    category: 1,
    difficulty: 4,
    rating: 5,
  },
  {
    id: 9,
    question: 'Which country has the most natural lakes?',
    answer: 'Canada',
    category: 3,
    difficulty: 3,
    rating: 4,
  },
  {
    id: 10,
    question: 'What is the tallest mountain in the world?',
    answer: 'Mount Everest',
    category: 3,
    difficulty: 1,
    rating: 4,
  },
  {
    id: 11,
    question: 'Who wrote the play Hamlet?',
    answer: 'William Shakespeare',
    category: 2,
    difficulty: 2,
    rating: 5,
  },
  {
    id: 12,
    question: 'What is the powerhouse of the cell?',
    answer: 'Mitochondria',
    category: 1,
    difficulty: 2,
    rating: 4,
  },
];
